services:
  db:
    image: postgres:15
    container_name: Sportly-db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    init: true
  
  frontend:
    build: 
      context: ./frontend
    container_name: Sportly-frontend
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    init: true
  backend:
    build: 
      context: ./backend
      target: builder
    container_name: Sportly-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    volumes:
      - ./backend:/app
      - /app/node_modules
    init: true
      
volumes:
  db_data:
